Implemented OMS importer package
Plaenkler/GoST pull request #5
Opened 2022-09-15 07:13 UTC by HighQualityWaschbaer

2022-09-15 19:52 UTC, Valentin-Kaiser commented on Application/pkg/config/config.go
> +	GOSTDBPath string `yaml:"GOSTDBPath"`
Inconsistent naming of variables. Check upper/lower case.

2022-09-15 19:52 UTC, Valentin-Kaiser commented on Application/pkg/importer/imports/converter/converter.go
> +		return 999
Why is 999 returned as value in case of error?

2022-09-16 06:44 UTC, HighQualityWaschbaer commented on Application/pkg/importer/imports/converter/converter.go
> +		return 999
999 is the designated id for "Sonstige"(other). This was specifically requested in the original importer software.

2022-09-16 12:49 UTC, Plaenkler commented on Application/pkg/config/config.go
> +	GOSTDBPath string `yaml:"GOSTDBPath"`
Updated in [31a8d6c](https://github.com/Plaenkler/GoST/pull/5/commits/31a8d6ca6ba3250af116883705a6ec743fb243bc)

2022-09-16 14:03 UTC, Plaenkler commented on Application/pkg/importer/imports/workshopInvoices.go
> +	//import workshop invoices
The comments should look like // *. //* is not allowed. Furthermore, capitalization is completely omitted.

2022-09-16 14:04 UTC, Plaenkler requested changes

2022-09-16 14:04 UTC, Plaenkler commented on Application/pkg/importer/imports/workshopInvoices.go
> +	//import workshop invoices
The comments should look like // *. //* is not allowed. Furthermore, capitalization is completely omitted.

2022-09-16 19:02 UTC, Plaenkler commented on Application/pkg/importer/imports/workshopInvoices.go
> +	//import workshop invoices
Solved in [1bbcba3](https://github.com/Plaenkler/GoST/pull/5/commits/1bbcba3da2034955576d452e1e252c18f4a987b8)

2022-09-16 20:31 UTC, Plaenkler approved these changes

2022-09-17 13:04 UTC, HighQualityWaschbaer reviewed
I can't approve this pull request as requested because it is mine but i approve this pr.

2022-09-17 13:25 UTC, merged

2022-09-18 00:19 UTC, Valentin-Kaiser commented on Application/pkg/importer/imports/agents.go
> +		dbf.Skip(1)
Error return value of dbf.Skip is not checked

2022-09-18 00:19 UTC, Valentin-Kaiser commented on Application/pkg/importer/imports/articles.go
> +		dbf.Skip(1)
Error return value of dbf.Skip is not checked

2022-09-18 00:19 UTC, Valentin-Kaiser commented on Application/pkg/importer/imports/customerErrors.go
> +		dbf.Skip(1)
Error return value of dbf.Skip is not checked

2022-09-18 00:19 UTC, Valentin-Kaiser commented on Application/pkg/importer/imports/detectedErrors.go
> +		dbf.Skip(1)
Error return value of dbf.Skip is not checked

2022-09-18 00:19 UTC, Valentin-Kaiser commented on Application/pkg/importer/imports/manufacturers.go
> +		dbf.Skip(1)
Error return value of dbf.Skip is not checked

2022-09-18 00:19 UTC, Valentin-Kaiser commented on Application/pkg/importer/imports/technicians.go
> +		dbf.Skip(1)
Error return value of dbf.Skip is not checked

2022-09-18 00:19 UTC, Valentin-Kaiser commented on Application/pkg/importer/imports/workshopInvoices.go
> +		wiDbf.Skip(1)
Error return value of dbf.Skip is not checked

2022-09-18 00:19 UTC, Valentin-Kaiser commented on Application/pkg/importer/imports/workshopInvoices.go
> +		dbf.Skip(1)
Error return value of dbf.Skip is not checked

2022-09-18 00:19 UTC, Valentin-Kaiser commented on Application/pkg/importer/imports/workshopInvoices.go
> +		dbf.Skip(1)
Error return value of dbf.Skip is not checked