Dev feature slu
Plaenkler/GoST pull request #64
Opened 2022-11-07 17:28 UTC by Plaenkler

Closes #10
Closes #10
Closes #10
Closes #10

2022-11-07 19:21 UTC, Valentin-Kaiser approved these changes

2022-11-08 08:49 UTC, HighQualityWaschbaer requested changes

2022-11-08 08:49 UTC, HighQualityWaschbaer commented on pkg/importer/importer.go
> +	}
Do you really wanna continue the import process if any of those imports have failed? This could lead to incomplete data being stored and displayed and could falsify the statistics being shown.

2022-11-08 08:52 UTC, Plaenkler commented on pkg/importer/importer.go
> +	}
The discussion has been played out more often. 😂 Yes it is so intentional.

2022-11-08 11:19 UTC, HighQualityWaschbaer approved these changes

2022-11-08 11:19 UTC, merged